### ISSUE TITLE
Gentoo: alsaequal searches in the wrong place for a moved library

### ISSUE THREAD

**Issue by traceur920** [raedwulf/alsaequal#2]
Hi, sorry to bring up an issue after so much time this project has been idle.

Gentoo has recently changed some profile settings and the compability symlink between /usr/lib and /usr/lib64 has been removed, but alsaequal seems to have the path where to search this library hardcoded. 
This makes alsaequal, on an x64 system, throw this error:

_"Failed to load plugin "/usr/lib/ladspa/caps.so": /usr/lib/ladspa/caps.so: cannot open shared object file: No such file or directory"_

As I'm barely able to read and understand the code, just enough to find this row
_[pcm_equal.c]:154	const char *library = "/usr/lib/ladspa/caps.so";_
can i suggest to adapt this to consider also the "/usr/lib64/" directory?
Or is there a more generic way of retrieving the caps.so library without knowing the exact position?

As this plugin is not actually officially supported by the Gentoo repository, but only through some overlays, feel free to do this changes or not, no big deal :)
Thank you!

**Comment by raedwulf** [comment]
Hey, oh wow!

I'm not the original upstream but I think the original author abandoned this:
https://github.com/charleseidsness/alsaequal

I didn't realise I became an upstream - I'll update the repository, I saw one of the forks from this repository has the necessary fix.

**Comment by raedwulf** [comment]
It should now be fixed.
